version: "3"
services:
  auth-db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5432:5432

  product-db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5433:5432

  sales-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=sales
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    ports:
      - 27017:27017

  sales-rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672

  product-api:
    build: "./product-api"
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  auth-api:
    build: "./auth-api"
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  sales-api:
    build: "./sales-api"
    environment:
      - PORT=8082
    ports:
      - 8082:8082
