INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Comic Books');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Movies');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Books');

INSERT INTO SUPPLIER (NAME) VALUES ('Panini Comics');
INSERT INTO SUPPLIER (NAME) VALUES ('Amazon');
INSERT INTO SUPPLIER (NAME) VALUES ('Netflix');

INSERT INTO PRODUCT (NAME, FK_CATEGORY, FK_SUPPLIER, AMOUNT_IN_STOCK, CREATED_AT) VALUES ('Crise nas Infinitas Terras', 1, 1, 10, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (NAME, FK_CATEGORY, FK_SUPPLIER, AMOUNT_IN_STOCK, CREATED_AT) VALUES ('Interestelar', 2, 2, 5, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (NAME, FK_CATEGORY, FK_SUPPLIER, AMOUNT_IN_STOCK, CREATED_AT) VALUES ('Harry Potter', 3, 2, 3, CURRENT_TIMESTAMP);
